# Site settings
title: Bucardo

# Build settings
markdown: kramdown

baseurl: ""

analytics: "UA-XXXXX-Y"

defaults:
    -
        scope:
            path: "" # Everything
        values:
            layout: "default"
            project: "bucardo"
    -
        scope:
            path: "check_postgres"
        values:
            project: "check_postgres"
    -
        scope:
            path: "DBIx-Safe"
        values:
            project: "dbix_safe"
    -
        scope:
            path: "tail_n_mail"
        values:
            project: "tail_n_mail"
    -
        scope:
            path: "Boxinfo"
        values:
            project: "boxinfo"
    -
        scope:
            path: "Pgsi"
        values:
            project: "pgsi"

gems:
    - jekyll-redirect-from

exclude: ['README', 'Gemfile', 'Gemfile.lock']
